### ISSUE TITLE
/bin/sh: 1: papermill: not found

### ISSUE THREAD

**Issue by x0152** [tiburon-security/jupyterlab_scheduler#2]
Hi!
I've created job `papermill /home/<jupyter-user>/test.ipynb /dev/null` When it called i will got error: `/bin/sh: 1: papermill: not found` but if i will execute the code in terminal then it are working
Under what user is the job executed?

**Comment by x0152** [comment]
I've found solution https://github.com/tiburon-security/jupyterlab_scheduler/pull/3

**Comment by jovanni-hernandez** [comment]
Sorry haven't had a chance to look at your prs this week because of work - I assume your pr didn't actually fix the issue so you reopened?

To answer your earlier question, it just runs in the user environment / context of whatever account started jupyterlab. For example, in docker jupyterlab is started under a custom account called "jovyan"

Without having had a chance to dig into the code, I assume potential issues could be:

- /bin/sh isn't your environments shell
- the plugins installer isn't automatically downloading and installing the python papermill package during install like it should

**Comment by x0152** [comment]
I've tried run command echo '$PATH'. I got output: ```/bin/:/usr/bin/``` but papermill is located ```/usr/local/bin```
I also tried to made links papermill in directory ```/usr/bin/```, but job failed with error beacose ipython couldn't found libraries that i used in notebook. 
It fix allows run command like it was executed by user.

**Comment by x0152** [comment]
> Sorry haven't had a chance to look at your prs this week because of work - I assume your pr didn't actually fix the issue so you reopened?
I think is better holding issue opened until you accept pull request or we will fix this in other way

**Comment by jovanni-hernandez** [comment]
Merged PR - thank you!
